<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>ea63aa9a-d40d-4ca9-92c6-3c0f4701d4b2</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_register_login</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/section[1]/div[1]/section[1]/div[2]/div[1]/div[1]/div[2]/p[2]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Register / Login')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Register / Login</value>
        <webElementGuid>7dcc131b-d960-4592-a912-06604e5d1c3c</webElementGuid>
    </webElementProperties>
</WebElementEntity>