<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>9e7223ea-97e8-45d5-9524-f498a8229f49</elementGuidId>
    <imagePath></imagePath>
    <name>button_pay_and_confirm_order</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/section[1]/div[1]/div[3]/div[1]/div[2]/form[1]/div[5]/div[1]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#submit</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'submit') and equals(@text,'Pay and Confirm Order')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Pay and Confirm Order</value>
        <webElementGuid>198100f6-4664-4f5e-8493-82a2b232a011</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>submit</value>
        <webElementGuid>198100f6-4664-4f5e-8493-82a2b232a011</webElementGuid>
    </webElementProperties>
</WebElementEntity>