<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>de577409-3384-48ce-a589-baf045f1e471</elementGuidId>
    <imagePath></imagePath>
    <name>input_expiry_month</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/section[1]/div[1]/div[3]/div[1]/div[2]/form[1]/div[3]/div[2]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="form-control\ card-expiry-month"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@name,'expiry_month') and equals(@type,'text')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>expiry_month</value>
        <webElementGuid>b2cd34dd-88d7-4baf-9e79-cb5d4bbea582</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>text</value>
        <webElementGuid>b2cd34dd-88d7-4baf-9e79-cb5d4bbea582</webElementGuid>
    </webElementProperties>
</WebElementEntity>