<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>24641843-5615-4cc6-b667-736b18c15827</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_tops_shirts</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/section[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[3]/div[2]/div[1]/ul[1]/li[2]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#Kids li:nth-child(2) &gt; a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'TOPS &amp; SHIRTS')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>TOPS &amp; SHIRTS</value>
        <webElementGuid>2cbdf60a-66d2-49f7-b84c-929fb0b2a1dc</webElementGuid>
    </webElementProperties>
</WebElementEntity>