<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>87ebb6e4-a93b-42d4-bbbe-5ef7769a1d90</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_api_testing</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/header[1]/div[1]/div[1]/div[1]/div[2]/div[1]/ul[1]/li[7]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="nav\ navbar-nav"] &gt; li:nth-child(7) &gt; a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'API Testing')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>API Testing</value>
        <webElementGuid>198100f6-4664-4f5e-8493-82a2b232a011</webElementGuid>
    </webElementProperties>
</WebElementEntity>