<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>e5e5fa42-39fd-4f0d-bcd5-5334386abf2f</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_api_testing</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/header[1]/div[1]/div[1]/div[1]/div[2]/div[1]/ul[1]/li[7]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'API Testing')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>API Testing</value>
        <webElementGuid>7dcc131b-d960-4592-a912-06604e5d1c3c</webElementGuid>
    </webElementProperties>
</WebElementEntity>