<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>20b3f347-72c5-4b5d-ab59-058f85703651</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_add_to_cart</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/section[2]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="col-sm-4"]:nth-child(3) [class="product-overlay"] [class="btn\ btn-default\ add-to-cart"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Add to cart')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Add to cart</value>
        <webElementGuid>b2cd34dd-88d7-4baf-9e79-cb5d4bbea582</webElementGuid>
    </webElementProperties>
</WebElementEntity>