<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>14185774-365c-4f52-a06a-a18764d17d02</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_test_case_10_verify_subscription_in_hom</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/section[1]/div[1]/div[11]/div[1]/div[1]/h4[1]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Test Case 10: Verify Subscription in home page')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Test Case 10: Verify Subscription in home page</value>
        <webElementGuid>7dcc131b-d960-4592-a912-06604e5d1c3c</webElementGuid>
    </webElementProperties>
</WebElementEntity>