<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>905247ee-486b-4950-ac1b-91e3b1aba5c5</elementGuidId>
    <imagePath></imagePath>
    <name>button_add_to_cart</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/section[1]/div[1]/div[1]/div[2]/div[2]/div[2]/div[1]/span[1]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[type="button"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'button') and equals(@text,'Add to cart')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Add to cart</value>
        <webElementGuid>5bf369ce-c729-4ede-b86a-bb81af09b38f</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>button</value>
        <webElementGuid>5bf369ce-c729-4ede-b86a-bb81af09b38f</webElementGuid>
    </webElementProperties>
</WebElementEntity>