<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>d5fbe915-1292-4ae1-a360-b4656767efdb</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_3_kookie_kids</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/section[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/ul[1]/li[7]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="nav\ nav-pills\ nav-stacked"] &gt; li:nth-child(7) &gt; a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'(3)
            KOOKIE KIDS')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>(3)
        KOOKIE KIDS</value>
        <webElementGuid>b2cd34dd-88d7-4baf-9e79-cb5d4bbea582</webElementGuid>
    </webElementProperties>
</WebElementEntity>