<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>9a4f5f6d-300d-4d34-8fc2-f4b7efec56de</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_contact_us</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/header[1]/div[1]/div[1]/div[1]/div[2]/div[1]/ul[1]/li[9]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>li:nth-child(9) &gt; a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Contact us')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Contact us</value>
        <webElementGuid>b2cd34dd-88d7-4baf-9e79-cb5d4bbea582</webElementGuid>
    </webElementProperties>
</WebElementEntity>