<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>4656108c-c7a9-492c-9a4b-4af069f85f2c</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_view_product</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/section[2]/div[1]/div[1]/div[2]/div[1]/div[5]/div[1]/div[2]/ul[1]/li[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="col-sm-4"]:nth-child(6) [class="choose"] a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'View Product')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>View Product</value>
        <webElementGuid>5bf369ce-c729-4ede-b86a-bb81af09b38f</webElementGuid>
    </webElementProperties>
</WebElementEntity>