<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>a4091445-fb17-4144-846f-2860850ebfd5</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_contact_us</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/header[1]/div[1]/div[1]/div[1]/div[2]/div[1]/ul[1]/li[9]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>li:nth-child(9) &gt; a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Contact us')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Contact us</value>
        <webElementGuid>5bf369ce-c729-4ede-b86a-bb81af09b38f</webElementGuid>
    </webElementProperties>
</WebElementEntity>