<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>6162319a-d1d5-4133-b48b-2db4c1ee8d34</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_place_order</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/section[1]/div[1]/div[7]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="btn\ btn-default\ check_out"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Place Order')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Place Order</value>
        <webElementGuid>b2cd34dd-88d7-4baf-9e79-cb5d4bbea582</webElementGuid>
    </webElementProperties>
</WebElementEntity>